#spring.datasource.url=jdbc:mysql://localhost:3306/jhsm?useUnicode=true&characterEncoding=utf8&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=cc

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jhsm?useUnicode=true&characterEncoding=utf8&autoReconnect=true"
    username: "root"
    password: "cc"


#cc.test.value=is it OK?
cc:
  cyg:
  test:
    value: "还乱麻？"

sms:
  accessKeyId: "LTAIWppOC2s0bZVU"
  accessKeySecret:  "r72nr6otE2MBV2WXbDmVzJQPduMavF"
  signName: "聚宏数码"
  templateCode: "SMS_130926106"
